name: mewsage
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  permission_handler: ^11.4.0
  http: ^0.13.6
  http_parser: ^4.0.2 
  path_provider: ^2.1.2
  path: ^1.8.3  
  tflite_flutter: ^0.11.0       
  file_picker: ^10.1.9         
  hive: ^2.2.3          
  hive_flutter: ^1.1.0   
  audioplayers: ^5.2.1
  intl: ^0.18.1
  sqflite: ^2.3.0
  uuid: ^3.0.7
  google_fonts: ^4.0.4
  record: ^5.0.4
  

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/cat.png
    - assets/cat_sound_classifier.tflite
 
  uses-material-design: true